### ISSUE TITLE
Can I use this without semantic release?

### ISSUE THREAD

**Issue by SomeKittens** [kentcdodds/publish-latest#10]
My project's major version is `0` so making lots of "breaking" changes before it's really ready for prod.  Can I use publish-latest to show off my built files without integrating semantic release just yet?

**Comment by kentcdodds** [comment]
Yes, you should be able to do that. You'll just have to manually tag the commit and push tags after `publish-latest` has run because this is something semantic-release does automatically. I might consider bringing this in as a configurable extra if you'd be interested in a PR for that.

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this one. Let me know if you have any follow-up questions.
