### ISSUE TITLE
Usage with Travis?

### ISSUE THREAD

**Issue by rstacruz** [kentcdodds/publish-latest#13]
I see scripts/*.sh has a reference to Travis. Can we use this inside Travis CI?

**Comment by kentcdodds** [comment]
That's the idea. You don't have to use this with Travis, but it works great with Travis and that's what my repositories do. You'll notice this repo has a [.travis.yml](https://github.com/kentcdodds/publish-latest/blob/master/.travis.yml). Here's [the build](https://travis-ci.org/kentcdodds/publish-latest).

**Comment by rstacruz** [comment]
in your setup, what takes care of tagging versions? semantic-release?

**Comment by kentcdodds** [comment]
Yes, I highly recommend you give it a look. You can follow along my free series on egghead.io: [How to Write an Open Source JavaScript Library](https://egghead.io/series/how-to-write-an-open-source-javascript-library)
