### ISSUE TITLE
Doesn't seem to fully clean up

### ISSUE THREAD

**Issue by gaearon** [kentcdodds/publish-latest#15]
After running `publish-latest` with default parameters in https://github.com/gaearon/react-dnd-html5-backend, my repo stays in `latest` branch. In addition, `travis/temp` isn't deleted. (I don't use Travis there.)

This is confusing because:
- I'd rather have the tool switch back to `master`
- Next time I run `publish-latest`, it crashes because `travis/temp` already exists

**Comment by kentcdodds** [comment]
Thanks for the feedback. This is definitely something that we could/should fix. Where are you running this out of curiosity? Locally?

**Comment by gaearon** [comment]
Yes, I just ran it locally after `npm publish`.

**Comment by kentcdodds** [comment]
Definitely want to cover the local use-case. I'll give this a look this weekend perhaps (sorry, I've got a few other things on my plate tonight). If you'd be interested, [the script](https://github.com/kentcdodds/publish-latest/blob/master/scripts/publish-latest.sh) is relatively simple and I'd welcome contributions :-)

**Comment by kentcdodds** [comment]
Note, master fails on Travis, so 1.1.3 was deprecated. I need to work out #14 as well before I can do another release.

**Comment by gaearon** [comment]
No urgency. I didn't realize this was supposed to run on Travis.

**Comment by kentcdodds** [comment]
Hey @gaearon, I'm sorry I haven't gotten to work on this for a while. With @mjackson's npmcdn.com now, I don't think that I'll personally need this tool anymore. I built it to solve the issues mentioned in my blogpost [Why I don't commit generated files to master](https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564) but npmcdn covers the major use-cases I had (I'm planning to drop official bower support).

I'm wondering if you would personally still benefit from this tool.

**Comment by gaearon** [comment]
Fair enough.
