### ISSUE TITLE
Fails to push latest branch

### ISSUE THREAD

**Issue by juristr** [kentcdodds/publish-latest#2]
_(continuing discussion from https://github.com/semantic-release/semantic-release/issues/75 here)_

@kentcdodds Hmm..ok. Set it up. Publishing to npm etc works. Tried to hook in your `publish-latest` plugin, but it failed. Any idea why: https://travis-ci.org/Swimlane/angular-model-factory/builds/82403298

```
...
> angular-model-factory@1.0.1 postpublish .
> publish-latest
stderr: fatal: 'travis/temp' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: Cannot update paths and switch to branch 'dist' at the same time.
Did you intend to checkout 'package.json' which can not be resolved as commit?
stdout: > PL >> setting global git config: latest,
> PL >> running git config --global user.email
> PL >> running git config --global user.name "latest"
> PL >> setting remote
> PL >> running git remote set-url origin travis/temp
> PL >> checking for dist package.json branch
> PL >> dist package.json does not exist on remote... creating it...
> PL >> running git checkout -b dist package.json
...
```

I don't get why it says this: `Please make sure you have the correct access rights`. 'Cause the push of the semantic-release created tag and GitHub release works just fine.

And it also seems to do a weird thing:

![image](https://cloud.githubusercontent.com/assets/542458/10122612/874d8486-651f-11e5-9109-479739c57015.png)

Any idea?

Thx!

**Comment by juristr** [comment]
Ok, found it :smile: . Problem was that the author wasn't reference properly in the `package.json`. Now it works like charm. Thanks a lot for this package!! So awesome and useful!

**Comment by kentcdodds** [comment]
Yay!!!! Glad it works for you :)

**Comment by juristr** [comment]
@kentcdodds Still, if I'm thinking about this, it might be that there's a bug when the author email is not specified, which is a valid case as according to the package.json specs is a valid case.

**Comment by kentcdodds** [comment]
Right, but all the inferred options can be specified :-)

**Comment by kentcdodds** [comment]
Hey @juristr, I'm posting about publish-latest in a blogpost and mentioning your repo. Do you mind reviewing it for me? DM me on twitter for a link :-)

**Comment by juristr** [comment]
Ya, sure. Would love to!
